Feat/support rax component
ice-lab/icepkg pull request #357
Opened 2022-06-15 04:19 UTC by ChrisCindy

- [x] 【待讨论】新增 componentFramework 字段标识当前开发的组件类型 (rax/react)
- [x] 支持开发 rax 组件
  - [x] dev 模式下 alias rax to rax-compat 以支持预览调试
  - [x] 更新 swc jsx 编译调整为 classic 模式 
- [x] transform 模式下支持 alias 
- [x] 更新文档中的错误

2022-06-21 09:40 UTC, wssgcg1213 requested changes
系系

2022-06-21 09:40 UTC, wssgcg1213 commented on examples/package/src/index.tsx
> +    setCount((c: number) => `${c}1`);
addCount 为啥是字符串拼接?!

2022-06-21 09:40 UTC, wssgcg1213 commented on packages/plugin-docusaurus/src/configureDocusaurus.mts
> +          rax: 'rax-compat'
还有一堆, 参考 https://github.com/ice-lab/ice-next/blob/release-next/packages/plugin-rax-compat/src/index.ts

2022-06-21 09:40 UTC, wssgcg1213 commented on packages/plugin-rax-component/package.json
> +  "name": "@ice/pkg-plugin-rax-component",
这里要不要考虑单独 `@icepkg` ?

2022-06-21 09:40 UTC, wssgcg1213 commented on packages/plugin-rax-component/package.json
> +  "license": "ISC",
licesese 和 author 去掉也行

2022-06-21 09:40 UTC, wssgcg1213 commented on packages/plugin-rax-component/package.json
> +    "@ice/pkg": "workspace: ^1.0.0",
这里依赖直接写正式版吧, 避免单包发的时候误传了, 这里 pnpm 也会link 的

2022-06-21 09:42 UTC, wssgcg1213 commented on packages/plugin-docusaurus/src/configureDocusaurus.mts
> +          rax: 'rax-compat'
对了, 这个 compat 逻辑启用的时候需要 tips 的吧, 主工程那边也是, 不要让用户无感, 毕竟出问题的时候还挺难查

2022-06-21 09:42 UTC, ChrisCindy commented on examples/package/src/index.tsx
> +    setCount((c: number) => `${c}1`);
lint 默认 fix 了，源码有问题，改一下。

2022-06-21 09:47 UTC, ChrisCindy commented on packages/plugin-rax-component/package.json
> +  "name": "@ice/pkg-plugin-rax-component",
所有 ICE PKG 的插件包名修改为 @icepkg/plugin-xxx，可以讨论一下

2022-06-21 09:55 UTC, wssgcg1213 commented on packages/plugin-rax-component/package.json
> +  "name": "@ice/pkg-plugin-rax-component",
恩 明天 TSC 讨论下 (当然, 不是很重要)

2022-06-22 12:47 UTC, wssgcg1213 approved these changes
![image](https://user-images.githubusercontent.com/3922719/68545933-c9347b80-040c-11ea-981d-ff40cf707ffa.png)

2022-06-27 06:53 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +      message: 'please select project type',
Capitalize the first letter `p` ~

2022-06-27 06:53 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'React component',
`React Component` 吧

2022-06-27 06:59 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +      message: 'please select project type',
这里有没有机会做到识别系统语言, 简单判断环境变量 $LANG 是否是 `zh` 打头, 认为是中文, 其它情况一律认定为 `en`  

为什么这里需要使用中文: 与用户界面交互的部分使用本地语言会提升 DX, 源码部分包括注释还是推荐用英文

2022-06-27 07:00 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'JS API',
怎么理解 `JS API`, 这里用 `通用 npm 包` 这个概念如何, 而且原来 rax api 体系也用的是 `universal` 这个词

2022-06-27 07:02 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'Rax component',
C 大写吧, 另外这里内置的组件模板目前仅限于 React/Rax, 后面会不会考虑 vue/ng/solid 等, 还有就是区块/模块这种需不需要内置进来, 不内置的话创建方式是怎么样的?

2022-06-27 07:27 UTC, ChrisCindy commented on packages/create-pkg/src/inquireProjectType.ts
> +      message: 'please select project type',
同意，我处理一下

2022-06-27 07:28 UTC, ChrisCindy commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'JS API',
非 UI 组件的 JS 库，或者叫 JS Library ?

2022-06-27 07:32 UTC, ChrisCindy commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'Rax component',
其他框架从精力上考虑暂时不接入，有需求可以贡献编译插件+新增模板来接入。

2022-06-27 07:59 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'JS API',
npm 包

2022-06-27 08:15 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +        name: 'Rax component',
+1

2022-07-04 03:42 UTC, wssgcg1213 submitted a review, later dismissed

2022-07-04 06:25 UTC, wssgcg1213 commented on packages/create-pkg/src/inquireProjectType.ts
> +      default: 'react-component',
这个值要跟下面的 value 对应

2022-07-04 08:19 UTC, ClarkXia approved these changes

2022-07-04 08:50 UTC, wssgcg1213 approved these changes

2022-07-04 08:54 UTC, merged

2022-07-06 03:06 UTC, SoloJiang commented on packages/plugin-rax-component/src/index.ts
> +          externalHelpers: false,
helpers 要注入么

2022-07-06 03:19 UTC, ChrisCindy commented on packages/plugin-rax-component/src/index.ts
> +          externalHelpers: false,
这里复用了 react component 编译的逻辑。@maoxiaoke 当时这里 externalHelpers 设为 false 有什么考虑吗？看起来设置为 true 貌似更合理。@swc/helpers 也默认作为组件的 dependencies 了

2022-07-12 10:05 UTC, maoxiaoke commented on packages/plugin-rax-component/src/index.ts
> +          externalHelpers: false,
不注入，项目依赖 https://github.com/ice-lab/ice-next/issues/95