featminify css bundle
ice-lab/icepkg pull request #485
Opened 2023-02-22 05:16 UTC by luhc228

2023-02-22 06:04 UTC, wssgcg1213 requested changes
minify 参数同时控制了 css 和 js 的压缩, 是否有这个必要, 以及是否有必要单独控制开关, 可以讨论一下看看

2023-02-23 04:31 UTC, TalkIsCheap0 commented
> minify 参数同时控制了 css 和 js 的压缩, 是否有这个必要, 以及是否有必要单独控制开关, 可以讨论一下看看

什么情况下会有只压缩其中一个的需求呢

2023-02-24 03:01 UTC, wssgcg1213 commented on examples/react-component/build.config.mts
> +    // ['@ice/pkg-plugin-docusaurus'],
这里不应该注释掉吧?

2023-02-24 03:02 UTC, wssgcg1213 commented on examples/react-component/package.json
> +    "sass-loader": "^13.2.0"
这里组件的 dev 依赖需要单独应用 sass 和 sass-loader 吗

2023-02-24 03:05 UTC, wssgcg1213 commented on packages/pkg/src/helpers/getRollupOptions.ts
> +  command: string;
这里不应该是枚举值吗

2023-02-24 05:50 UTC, luhc228 commented on examples/react-component/package.json
> +    "sass-loader": "^13.2.0"
sass-loader 要额外依赖一下，原因是 docusaurus 不能 resolve 到：https://github.com/rlamana/docusaurus-plugin-sass/pull/25

sass 是因为 rollup-plugin-style 需要依赖它来做编译（其实如果按照这样，plugin-docusaurus 都不需要依赖 sass 了）

2023-02-24 06:24 UTC, wssgcg1213 commented on examples/react-component/package.json
> +    "sass-loader": "^13.2.0"
这个会有文档说明吗

2023-02-24 06:24 UTC, wssgcg1213 approved these changes

2023-02-24 07:01 UTC, luhc228 commented on examples/react-component/package.json
> +    "sass-loader": "^13.2.0"
要加一下的

2023-02-24 07:48 UTC, merged